<?php

namespace AppBundle\Repository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
  function getTasks()
  {
    $qb = $this->createQueryBuilder('u')
             ->select('u')
             ->getQuery()
             ->getArrayResult();

             return $qb;
  }
}
